import requests

url = "https://exercisedb-api1.p.rapidapi.com/api/v1/exercises"
querystring = {"name": "Bench Press", "keywords": "chest workout,barbell", "limit": "10"}
headers = {
    "x-rapidapi-key": "fbb433648bmsh752273990de18c5p101058jsn8213e24565e3",
    "x-rapidapi-host": "exercisedb-api1.p.rapidapi.com"
}
response = requests.get(url, headers=headers, params=querystring)
print(response.json())  # Should show exercise data
	<option value="5.0">Aerobic Dance (Casual)</option>
						<option value="6.5">Aerobic Dance (Moderate)</option>
						<option value="7">Aerobic Dance (Intense)</option>
						<option value="8.0">Basketball (Game)</option>
						<option value="6.0">Basketball (Non-Game, General)</option>
						<option value="4.5">Basketball (Shooting Baskets)</option>
						<option value="8.0">Calisthenics (Intense)</option>
						<option value="3.5">Calisthenics (Moderate)</option>
						<option value="4.0">Cycling (5.5 mph)</option>
						<option value="8.0">Cycling (12-13 mph)</option>
						<option value="12.0">Cycling (16-19 mph, Racing)</option>
						<option value="3.0">Dancing (Casual)</option>
						<option value="5.5">Dancing (Fast)</option>
						<option value="9.0">Football (Competitive)</option>
						<option value="8.0">Football (Flag, Touch, General)</option>
						<option value="2.5">Football (Playing Catch)</option>
						<option value="3.0">Frisbie (General)</option>
						<option value="8.0">Frisbie (Ultimate)</option>
						<option value="4.5">Golf (Carry Clubs)</option>
						<option value="3.5">Golf (with Cart)</option>
						<option value="4.0">Gymnastics</option>
						<option value="6.0">Hiking (Cross Country)</option>
						<option value="3.0">Housework</option>
						<option value="12.0">Jump Rope (Fast)</option>
						<option value="8.0">Jump Rope (Slow)</option>
						<option value="5.0">Kayaking</option>
						<option value="7.0">Kickball</option>
						<option value="1.0">Lying Quietly</option>
						<option value="10.0">Martial Arts</option>
						<option value="4.0">Motocross</option>
						<option value="7.0">Racquetball (Casual)</option>
						<option value="10.0">Racquetball (Competitive)</option>
						<option value="8.0">Rock/Mountain Climbing</option>
						<option value="11.0">Rollerblading/skating (Casual)</option>
						<option value="12.0">Rollerblading/skating (Fast)</option>
						<option value="10.5">Rowing Machine (Extreme)</option>
						<option value="7.0">Rowing Machine (Moderate)</option>
						<option value="7.0">Running (Jogging/General)</option>
						<option value="8.0">Running (5 mph, 12min mile)</option>
						<option value="10.0">Running (6 mph, 10min mile)</option>
						<option value="11.5">Running (7 mph, 8.5min mile)</option>
						<option value="13.5">Running (8 mph, 7.5min mile)</option>
						<option value="16.0">Running (10 mph, 6min mile)</option>
						<option value="9.0">Running (Cross Country)</option>
						<option value="5.0">Snow Skiing (Downhill - General)</option>
						<option value="6.0">Snow Skiing (Downhill - Moderate)</option>
						<option value="8.0">Snow Skiing (Downhill - Extreme)</option>
						<option value="7.0">Snow Skiing (Cross Country - General)</option>
						<option value="8.0">Snow Skiing (Cross Country - Moderate)</option>
						<option value="9.0">Snow Skiing (Cross Country - Brisk)</option>
						<option value="8.0">Snow Shoeing</option>
						<option value="1.5">Sitting (Office work)</option>
						<option value="1.0">Sitting (Quietly)</option>
						<option value="5.0">Skateboarding</option>
						<option value="10.0">Soccer (Competitive)</option>
						<option value="7.0">Soccer (Casual, General)</option>
						<option value="5.0">Softball</option>
						<option value="12.0">Squash</option>
						<option value="8.0">Stair/Ladder Climbing</option>
						<option value="2.3">Standing (Office work)</option>
						<option value="1.0">Standing (Quietly)</option>
						<option value="2.5">Stretching/Hatha Yoga</option>
						<option value="7.0">Swimming (Casual)</option>
						<option value="10.0">Swimming (Vigorous)</option>
						<option value="4.0">Table Tennis/Ping Pong</option>
						<option value="4.0">Tai Chi</option>
						<option value="6.0">Tennis (Doubles)</option>
						<option value="8.0">Tennis (Singles)</option>
						<option value="3.0">Volleyball (Casual Indoor/Grass)</option>
						<option value="8.0">Volleyball (Beach)</option>
						<option value="8.0">Volleyball (Competitive)</option>
						<option value="2.0">Walking (2 mph, Casual Pace)</option>
						<option value="3.3">Walking (3 mph, Moderate Pace)</option>
						<option value="3.8">Walking (3.5 mph, Brisk Pace)</option>
						<option value="5.0">Walking (4 mph, Very Brisk Pace)</option>
						<option value="9.0">Walking (5.0, Fast Pace)</option>
						<option value="10.0">Water Polo</option>
						<option value="6.0">Weight Training (Intense)</option>
						<option value="3.0">Weight Training (Normal)</option>
						<option value="5.5">Yardwork (Heavy)</option>
						<option value="4.0">Yardwork (Regular)</option>